name: black

on:
  pull_request:
    paths:
      - '**.py'
  push:
    branches:
      - master

jobs:
  python-black:
    name: Python Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Black
        uses: cytopia/docker-black@0.8
        with:
          path: '.'
      - name: Python Black
        uses: cytopia/docker-black@0.8
        with:
          path: 'bin/lxa-iobus-lpc11xxcanisp-invoke'
      - name: Python Black
        uses: cytopia/docker-black@0.8
        with:
          path: 'bin/lxa-iobus-lpc11xxcanisp-program'
      - name: Python Black
        uses: cytopia/docker-black@0.8
        with:
          path: 'bin/lxa-iobus-server'
